#!/usr/bin/env node
// Mirror the claude-works README gallery into the landing profile's
// "Selected work" section (github.com/Satejp10/Satejp10).
//
// Reads the generated gallery block (between <!-- GALLERY:START --> and
// <!-- GALLERY:END -->) from this repo's README.md, rewrites the thumbnail
// <img src> paths from repo-relative (assets/thumbnails/…) to absolute
// raw.githubusercontent.com URLs — repo-relative image paths don't resolve
// when the markup is embedded from another repo — and replaces the block
// between <!-- SELECTED-WORK:START --> and <!-- SELECTED-WORK:END --> in the
// target README passed as the first argument. Everything else in the gallery
// (links, titles, layout) is copied verbatim, so the two stay identical.
//
// Run: node .github/scripts/sync-landing.mjs path/to/landing/README.md
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(fileURLToPath(import.meta.url), '../../..');
const WORKS_README = path.join(ROOT, 'README.md');
// Thumbnails live in claude-works; from another repo they must be absolute.
const RAW_PREFIX = 'https://raw.githubusercontent.com/Satejp10/claude-works/main/assets/thumbnails/';

const GALLERY_RE = /<!-- GALLERY:START -->\s*([\s\S]*?)\s*<!-- GALLERY:END -->/;
const SELECTED_RE = /<!-- SELECTED-WORK:START -->[\s\S]*?<!-- SELECTED-WORK:END -->/;

async function main() {
  const target = process.argv[2];
  if (!target) throw new Error('Usage: node sync-landing.mjs <landing README path>');

  const worksMd = await readFile(WORKS_README, 'utf8');
  const m = worksMd.match(GALLERY_RE);
  // The works gallery is generated by gen-thumbnails.mjs; missing markers here
  // means this repo is broken, so fail loudly.
  if (!m) throw new Error('Gallery markers not found in works README.md — nothing to mirror.');

  // Repo-relative thumbnail paths → absolute raw URLs. Only the <img src>
  // changes; hrefs (live Pages / external demos) are already absolute.
  const table = m[1].trim().replaceAll('src="assets/thumbnails/', `src="${RAW_PREFIX}`);

  const landingMd = await readFile(target, 'utf8');
  // A landing repo that hasn't opted in (no markers) is not an error — just skip,
  // so this repo's CI never goes red over the profile repo's state.
  if (!SELECTED_RE.test(landingMd)) {
    console.warn(`SELECTED-WORK markers not found in ${target} — skipping (nothing to update).`);
    return;
  }

  const block = `<!-- SELECTED-WORK:START -->\n${table}\n<!-- SELECTED-WORK:END -->`;
  const next = landingMd.replace(SELECTED_RE, block);
  if (next === landingMd) { console.log('Selected work already up to date.'); return; }

  await writeFile(target, next);
  console.log(`Selected work block updated in ${target}.`);
}

main().catch((e) => { console.error(e); process.exit(1); });
